# Ограничения длины полей
SKILL_NAME_MAX_LENGTH = 124
PROJECT_NAME_MAX_LENGTH = 200

# Коды статусов проекта
PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

PROJECT_STATUS_CHOICES = (
    (PROJECT_STATUS_OPEN, "Open"),
    (PROJECT_STATUS_CLOSED, "Closed"),
)

# Пагинация каталога проектов
PROJECTS_PER_PAGE = 12

# Константы для тестов
OWNER_EMAIL = 'owner@test.com'
OWNER_PASSWORD = 'pass123'
OWNER_NAME = 'Project'
OWNER_SURNAME = 'Owner'
OWNER_PHONE = '+79004444444'

PROJECT_NAME = 'Test Project'

LIST_OWNER_EMAIL = 'test@test.com'
LIST_OWNER_PASSWORD = 'pass123'
LIST_OWNER_NAME = 'Test'
LIST_OWNER_SURNAME = 'User'
LIST_OWNER_PHONE = '+79005555555'

LIST_PROJECT_NAME = 'Project 1'

CREATOR_EMAIL = 'creator@test.com'
CREATOR_PASSWORD = 'pass123'
CREATOR_NAME = 'Creator'
CREATOR_SURNAME = 'User'
CREATOR_PHONE = '+79006666666'

VIEWER_EMAIL = 'viewer@test.com'
VIEWER_PASSWORD = 'pass123'
VIEWER_NAME = 'Viewer'
VIEWER_SURNAME = 'User'
VIEWER_PHONE = '+79007777777'

DETAIL_PROJECT_NAME = 'Detail Project'

SKILL_NAME = 'Python'